[changelog]
header = ""
body = """
{% if version %}## {{ version }} — {{ timestamp | date(format="%Y-%m-%d") }}{% else %}## Unreleased{% endif %}

{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}
{% for commit in commits %}
- {{ commit.message | split(pat="\n") | first | trim }}\
{% endfor %}
{% endfor %}\n
"""
trim = true
footer = ""

[git]
conventional_commits = false
filter_unconventional = false
commit_parsers = [
  { message = "^Merge", skip = true },
  { message = "(?i)readme|logo|cargo\\.toml|version|alignment|heading", skip = true },
  { message = "^feat|^add", group = "Added" },
  { message = "^fix|^bug", group = "Fixed" },
  { message = "^refactor|^replace|^swap|^cleanup", group = "Changed" },
  { message = ".*", group = "Changed" },
]
filter_commits = true
tag_pattern = "v[0-9].*"
topo_order = false
sort_commits = "oldest"
